version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
  redis:
    image: redis
    ports:
      - "6379:6379"
